# SITE CONFIGURATION
title: phereford's blog # your site title
author: Patrick Hereford # You :P
description: > # Meta description of Homepage
  Providing leadership and ideas pertaining to software engineering management.
  All posts on this blog are my own and come from my own experience running and
  growing teams. YMMV.

baseurl: "/"
url: "https://p.hereford.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/icons/android-chrome-384x384.png"

# SEO PLUGIN
social:
  name: Patrick Hereford
  links:
    - https://twitter.com/phereford
    - https://www.linkedin.com/in/phereford
    - https://github.com/phereford

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Books', link: '/books'}
  - {name: 'PH Readme', link: '/readme.html'}
  #- {name: 'About', link: '/about'}
  #- {name: 'Contact', link: '/contact'}
  #- {name: 'My Readme', link: '/readme'}

tagline: >
  Focused Software Engineering, Management and Leadership Topics

hero_img: posts/code-image.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: patrick@hereford.io # email for form submission

twitter_username: phereford # replace with your_twitter_username or comment to remove link from footer
github_username:  phereford # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: phereford575 # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-NJSBPTN # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
